### PR TITLE
Added username on message reply

### PR DESCRIPTION
**Pull request by Matthiasclee**

### CODE REVIEW

**Comment by iilatt** [comment]
I'm afraid this code won't work for multiple users at the same time. That's why there was a global listener for a new websocket message. If you add a new listener every time they will get all messages regardless. One way to fix this would be to make a separate websocket connection every time but this wouldn't be the fastest solution.

**Comment by Matthiasclee** [comment]
Oh, ok. I need to figure out some way to make the websocket return the user as well without modifying that code.

**Comment by iilatt** [comment]
My only idea is to have a global lookup array of current requests. That will also enable us to check if someone is already requesting something so we can limit it to 1 per user for example.

**Comment by iilatt** [comment]
Also please use ES6 standard for example when defining variables.

**Comment by Matthiasclee** [comment]
Ok

**Pull request closed without merging**
